<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 21.02.2019
 * Time: 7:02
 */

namespace app\components;


use app\models\Activity;
use yii\base\Component;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;

class ActivityComponent extends Component
{
    /** @var string class of activity entity */
    public $activity_class;

    /**
     * @return mixed
     */
    public function beforeValidate()
    {
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function init() {
         parent::init();

         if(empty($this->activity_class)){
             throw  new \Exception('Attribute activity_class is required');
         }
    }

    /**
     * @param array
     * @return Activity
     */
    public function getModel($params = null) {
        /** @var Activity $model */
        $model = new $this->activity_class;
        if($params && is_array($params)) {
            $model->load($params);
        }
        return $model;
    }

    /**
     * @param $model Activity
     * @return bool
     */
    public function createActivity(&$model):bool {
        if($model->validate()) {
            $model->images = UploadedFile::getInstances($model, 'images');
            $path = $this->getPathSaveFile();
            foreach ($model->images as $image) {
                $name = mt_rand(0, 9999) . time() . '.' . $image->getExtension();
                if(!$image->saveAs($path.$name)) {
                    $model->addError('images', 'Файл не удалось переместить');
                    return false;
                }
                $model->uploadedImages[] = $name;
            }
            return true;
        }
    }

    private function getPathSaveFile() {
        return \Yii::getAlias('@app/web/upload/');
    }
}