<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19.02.2019
 * Time: 22:54
 */

namespace app\base;


use yii\web\Controller;

class BaseController extends Controller
{
     // сохраняем последнюю посещенную страницу
    public function afterAction($action, $result)
    {
        $session = \Yii::$app->session;
        $session->set('lastPage', \Yii::$app->request->absoluteUrl);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}